### ISSUE TITLE
Issue on page /ml.html

### ISSUE THREAD

**Issue by JorritJS** [statisticalbiotechnology/dsbook#2]
1.4. Machine Supervised Learning is not clear to me. The term is not a formally defined one in my understanding, and this created some confusion when trying to find background information. Perhaps it would fit into two paragraphs: self-supervised learning or reinforcement learning.

**Comment by percolator** [comment]
You are absolutely right! I intended to write about self-supervised learning. 

I skipped reinforcement learning in this part, mostly because one need to stop at some point.

Closed by 22ea4bea86c784a1e9f08a71c7f3e8a6a7bd6537
