### ISSUE TITLE
details Regularization

### ISSUE THREAD

**Issue by gsjoblo** [statisticalbiotechnology/dsbook#4]
# Norms
Some students will <ins>only</ins> have heard of L1 norm as Max-norm, and L2 as euclidean norm.
Showing these as related to the vector, i.e. L1 is sum of vector components, "Taxicab" style, and L2 as the absolute length of the vector may help as well. 
Worth clarifying that L1 will primarily punish single parameters while L2 punishes the whole - which opens up for understanding of when the combination is useful.

**Comment by percolator** [comment]
i will leave this issue open for now

**Comment by percolator** [comment]
Thanks, I will try to use your suggestions when talking about it in class in next incarnation of the corse.
