### ISSUE TITLE
Issue on page /supervised/xval.html

### ISSUE THREAD

**Issue by benstr4** [statisticalbiotechnology/dsbook#5]
In section 7.1.2, the text is a bit confusing, with remnants of deleted sentences.

In section 7.2.1, you talk about how alpha is the hyperparameter we want to determine for LASSO regression, but then you determine a range of values for "lambda" and iterate over them in the grid search. If i remember correctly these are the same, but the wording is very confusing. you could add a clarification that alpha in the code represents lambda in the equation from 3.3.

**Comment by percolator** [comment]
I removed the ref to \lambda, as I agree it was confusing.

Closed by 83145675fb1d4cf4213305c897006b053cd0103e
