### ISSUE TITLE
Issue on page /supervised/xval.html

### ISSUE THREAD

**Issue by MatildeRFonseca** [statisticalbiotechnology/dsbook#7]
Under this section _7.1.2. Cross Validation to the Rescue_, 

"**Idealy**, one would like to train and test on as much data as possible. There is To evaluate how well a model will perform on new, unseen data, it’s important to use validation techniques such as cross validation."

There is a typo in the word in bold and the start of the second sentence seems to be a bit off for me, perhaps "Therefore to evaluate..." could make it better.

Hope this helps!

**Comment by percolator** [comment]
This is helpful. I updated accordingly.

Patch a94c7ba9dbb4f3a9b28997b602df950336609538
