### ISSUE TITLE
Issue on page /statistics/multiple.html

### ISSUE THREAD

**Issue by jahlwe** [statisticalbiotechnology/dsbook#9]
I'd like to comment on these passages under 15.1.2

The very first sentence: "The Benjamini-Hochberg (BH) procedure is a popular method for controlling the False Discovery Rate (FDR), **which is the expected proportion of false positives among the rejected hypotheses**."
- Would it be more clear to state "... which is the expected proportion of false positives among the rejected NULL hypotheses"? Perhaps technically it is redundant, if the idea is that the only thing we are ever really taking a stance towards is the null hypothesis. But, reading it for the first one or two times made me scratch my head until I realized that what was meant was an expected proportion of false positives among our prima facie FINDINGS, that is, among the tests for which we have rejected the null hypothesis.

Same thing here, under the threshold formula graphic: "... here i is the rank of the p value and m is the total number of hypotheses. 4. Find the largest i for which p(i) < i/m * q. Reject all (NULL?) hypotheses with 
 values less than or equal to p(i).

For your consideration! I don't know if this counts as a pull request, for the questions credit - learning GitHub slowly.
/Jacob Ahlberg, Systems Biology reader

**Comment by percolator** [comment]
Thanks, really good comments!

I must have been tired when writing this; I have inverted the logic in a couple of different places in the text.

Your first comment is correct. My statement is simply incorrect. I updated accordingly.

The second comment. The point of the procedure is that we *accept* all hypotheses below the threshold, so whatever I wrote before is wrong. However, in a real application, we would not know if they are under H_0 or H1, so we have to accept/reject them regardless if they stem from null or not. 

Closed by e54d608e54b0ad49003a8cbb034c739ca58fa63c
